colors:
    - black
    - blue
    - brown
    - dark
    - golden
    - gray
    - grey
    - green
    - indigo
    - light
    - orange
    - pink
    - purple
    - red
    - violet
    - white
    - yellow
modifiers:
    - coarse
    - coarsely
    - dark
    - fine
    - finely
    - light
    - medium
    - med\.
    - pale
    - poorly
    - strongly
    - weakly
textures:
    - altered
    - anhedral
    - apophysis
    - baked
    - banded
    - blocks?
    - botryoidal
    - boudins?
    - brecciated
    - coarse
    - deformed
    - dense
    - detrital
    - digested
    - disseminated
    - equigranular
    - euhedral
    - fibrous
    - fine
    - float
    - folded
    - foliated
    - fractured
    - fragments?
    - fragmentary
    - gneissic
    - grained
    - granular
    - granulated
    - grit
    - gritty
    - inequigranular
    - lacy
    - laminated
    - lamellae?
    - lens
    - lenses
    - massive
    - megacrystic
    - megacrysts?
    - metamorphosed
    - microfolded
    - microfractured
    - monomict
    - pebbles?
    - phenocrystic
    - phenocrysts?
    - platy
    - pleochroic
    - polymict
    - porphyroblastic
    - porphyroblasts?
    - schistose
    - schlieren
    - shatter ?cones?
    - sheared
    - shocked
    - shock-fractured
    - slaty
    - slicken-?sided
    - slicken-?sides?
    - synhedral
    - variegated
    - vitrified
    - weathered
stopwords:
    - and
    - assemblage
    - by
    - caledonian
    - coated
    - coating
    - cut
    - cutting
    - from
    - in
    - on
    - with
endings:
    - ally
    - ceous
    - e
    - ey
    - ian
    - ic
    - ically
    - iferous
    - ized
    - ium
    - oan
    - ose
    - ous
    - y
capex:
    # Elements
    - H
    - He
    - Li
    - Be
    - B
    - C
    - N
    - O
    - F
    - Ne
    - Na
    - Mg
    - Al
    - Si
    - P
    - S
    - Cl
    - Ar
    - K
    - Ca
    - Sc
    - Ti
    - V
    - Cr
    - Mn
    - Fe
    - Co
    - Ni
    - Cu
    - Zn
    - Ga
    - Ge
    - As
    - Se
    - Br
    - Kr
    - Rb
    - Sr
    - Y
    - Zr
    - Nb
    - Mo
    - Tc
    - Ru
    - Rh
    - Pd
    - Ag
    - Cd
    #- In
    - Sn
    - Sb
    - Te
    - I
    - Xe
    - Cs
    - Ba
    - La
    - Ce
    - Pr
    - Nd
    - Pm
    - Sm
    - Eu
    - Gd
    - Tb
    - Dy
    - Ho
    - Er
    - Tm
    - Yb
    - Lu
    - Hf
    - Ta
    - W
    - Re
    - Os
    - Ir
    - Pt
    - Au
    - Hg
    - Tl
    - Pb
    - Bi
    - Po
    - At
    - Rn
    - Fr
    - Ra
    - Ac
    - Th
    - Pa
    - U
    - 2+
    - 3+
    - 4+
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    # Mutli-element strings
    - AlCu
    - AlCuFeH
    - BaFe
    - BaNa
    - BiCuPb
    - CaFe
    - CaFeFe
    - CaFeMg
    - CaMnFe
    - CaMnMn
    - CaMnMg
    - ClHMn
    - FeHZn
    - KFe
    - KFeNa
    - KMnNa
    - KNa
    - MnFeMg
    - MnMnFe
    - MnMnMg
    - MnMnMn
    - NaFeMg
    - NaMnMg
    - NH
    - OH
    - PbFe
    - SiO
    - SiO2
    - SrFe
    - SrTiZr
    - ZnS
    - CaClFeHMnNaNbREEZr
    - CaClFeHMnNaNbSrZr
    - CaClFeHMnNaREESrTiZr
    - CaCeHMnNaNbSrZr
    - CaClFeHMgMnNaNbZr
    - CaCeClHMnNaZr
    - ClHMgMnZn
    # Meteorites
    - (CB([0-9]?(\.[0-9]+)?)?)
    - (CH([0-9]?(\.[0-9]+)?)?)
    - (CK([0-9]?(\.[0-9]+)?)?)
    - (CM([0-9]?(\.[0-9]+)?)?)
    - (CR([0-9]?(\.[0-9]+)?)?)
    - (CV([0-9]?(\.[0-9]+)?)?)
    - (CO([0-9]?(\.[0-9]+)?)?)
    - (CI([0-9]?(\.[0-9]+)?)?)
    - (EH([0-9]?(\.[0-9]+)?)?)
    - (EL([0-9]?(\.[0-9]+)?)?)
    - (H([0-9]?(\.[0-9]+)?)?)
    - HED
    - IAB
    - IA
    - IB
    - IC
    - ID
    - IE
    - IIAB
    - IICD
    - IIA
    - IIB
    - IIC
    - IID
    - IIE
    - IIF
    - IIG
    - IIIAB
    - IIICD
    - IIIA
    - IIIB
    - IIIC
    - IIID
    - IIIE
    - IIIF
    - IVAB
    - IVA
    - IVB
    - (L([0-9]?(\.[0-9]+)?)?)
    - (LL([0-9]?(\.[0-9]+)?)?)
    - SNC
    - I
    - II
    - III
    - IV
    - V
    - VI
    - VII
    - VIII
    - IX
    - X
    # Names
    - Bergholz
    - Biggs
    - Cerny
    - Chen
    - Chukanov
    - Frenzel
    - Hauser
    - Hogarth
    - Juve
    - Köhler
    - Larsen
    - Leake
    - Mazzi
    - Moore
    - Munno
    - Nicol
    - Rost
    - Shephard
    - Voloshin
    # Words that can be expressed as a string of elements
    - Uvite
    # Miscellaneous
    - MSH
    - SS
    - TAS
    - UK
